project:
  type: website
  output-dir: docs

website:
  title: "La guarida de los datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



