project:
  type: website
  output-dir: docs

website:
  title: "La guarida de los datos"
  favicon: Img/logo04.png
  navbar:
    title: false
    logo: Img/logo05.svg
    left:
      - href: index.qmd
        text: Principal
      - href: about.qmd
        text: Acerca



format:
  html:
    theme: vapor
    css: styles.css
    toc: true



