{
  "text-color": "#F7FAFC",
  "background-color": "#123047",
  "line-number-color": "#B8CAD6",
  "line-number-background-color": null,
  "text-styles": {
    "Alert": {
      "text-color": "#FF7A5C",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Annotation": {
      "text-color": "#B8CAD6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Attribute": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#B8CAD6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#B8CAD6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Constant": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Documentation": {
      "text-color": "#B8CAD6",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#FF7A5C",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#FF7A5C",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#F7FAFC",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#F7FAFC",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#38D6CF",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#F7FAFC",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#F2B544",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#FF7A5C",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    }
  }
}
